mmccore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('team/', views.TeamView.as_view(), name='team'),
    path('causes/', views.CauseListView.as_view(), name='causes'),
    path('causes/<slug:slug>/', views.CauseDetailView.as_view(), name='cause_detail'),
    path('programs/', views.ProgramListView.as_view(), name='programs'),
    path('programs/<slug:slug>/', views.ProgramDetailView.as_view(), name='program_detail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('volunteer/', views.VolunteerCreateView.as_view(), name='volunteer'),
    path('documents/', views.DocumentListView.as_view(), name='documents'),
    path('blog/', views.BlogListView.as_view(), name='blog_list'),
    path('blog/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('events/', views.EventListView.as_view(), name='event_list'),
    path('events/<slug:slug>/', views.EventDetailView.as_view(), name='event_detail'),
    path('shop/', views.ProductListView.as_view(), name='shop'),
    path('donate/', views.DonateView.as_view(), name='donate'),
]

templates/blog-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ post.title }} - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Blog Details</span>              
             <h2 class="title-animation">{{ post.title }}</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Blog Details Section -->
<section class="blog-details section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <article class="blog-single-content-wrap">
                    <div class="thumbnail mb-4">
                        {% if post.image %}
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid rounded">
                        {% else %}
                        <img src="{% static 'images/four-7.png' %}" alt="{{ post.title }}" class="img-fluid rounded">
                        {% endif %}
                    </div>
                    
                    <ul class="post-meta mb-3">
                        <li><i class="fa-regular fa-user"></i> <span>Written by:</span> <span class="user">{{ post.author|default:"Admin" }}</span></li>
                        <li><i class="fa-solid fa-calendar-days"></i> {{ post.published_date|date:"F d, Y" }}</li>
                    </ul>

                    <div class="entry-content">
                        <section class="blog-main cm-details p-0">
                            <div class="cm-details__content">
                                <h3 class="title-animation mb-4">{{ post.title }}</h3>
                                <div class="post-text">
                                    {{ post.content|safe }}
                                </div>
                            </div>
                        </section>
                    </div>

                    <div class="blog-details-footer d-flex justify-content-between align-items-center mt-5 p-4 bg-light rounded">
                        <div class="left">
                            <h5 class="title d-inline-block me-2">Category:</h5>
                            <ul class="tags d-inline-block list-unstyled m-0">
                                <li class="d-inline-block"> <a href="#" class="btn btn-sm btn-outline-secondary">{{ post.category.name|default:"General" }}</a></li>
                            </ul>
                        </div>
                        <div class="right">
                            <h5 class="title d-inline-block me-2">Share:</h5>
                            <ul class="social-icon d-inline-block list-unstyled m-0">
                                <li class="d-inline-block me-2"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="d-inline-block me-2"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li class="d-inline-block me-2"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            </ul>
                        </div>
                    </div>

                    <!-- Navigation -->
                    <div class="single-post-navigation d-flex justify-content-between mt-5 pt-4 border-top">
                        <div class="prev-post">
                            {% if post.get_previous_by_published_date %}
                            <a href="{% url 'web:blog_detail' post.get_previous_by_published_date.slug %}">
                                <i class="fa fa-arrow-left"></i> Prev Post
                            </a>
                            {% endif %}
                        </div>
                        <div class="next-post text-end">
                            {% if post.get_next_by_published_date %}
                            <a href="{% url 'web:blog_detail' post.get_next_by_published_date.slug %}">
                                Next Post <i class="fa fa-arrow-right"></i>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </article>

                <!-- Comments section (simplified) -->
                <div id="comments" class="comments-area mt-5 pt-5 border-top">
                    <div id="respond" class="comment-respond">
                        <h3 id="reply-title" class="comment-reply-title">Leave A Comment</h3>
                        <form action="#" method="post" id="commentform" class="comment-form mt-4">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <input type="text" name="author" class="form-control" placeholder="Name" required>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input type="email" name="email" class="form-control" placeholder="Email" required>
                                </div>
                                <div class="col-12 mb-3">
                                    <textarea name="comment" class="form-control" placeholder="Comment..." rows="5" required></textarea>
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary">Post Comment</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/blog-grid.html
{% extends "base.html" %}
{% load static %}

{% block title %}Blog - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Our Latest News</span>              
             <h2 class="title-animation">Blog Grid</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Blog Section -->
<section class="blog blog-two section-padding">
    <div class="container">
        <div class="row gutter-40">
            {% for post in posts %}
            <div class="col-12 col-lg-4 mb-4">
                <div class="blog__single-wrapper pb-3">
                    <div class="blog__single van-tilt">
                        <div class="blog__single-inner">
                            <div class="blog__single-meta">
                                <p><i class="icon-user"></i>{{ post.author|default:"Admin" }}</p>
                                <p><i class="icon-calendar"></i>{{ post.published_date|date:"d M Y" }}</p>
                            </div>
                            <div class="blog__single-content">
                                <h5><a href="{% url 'web:blog_detail' post.slug %}">{{ post.title }}</a></h5>
                                <p>{{ post.excerpt|default:post.content|truncatewords:20 }}</p>
                            </div>
                            <div class="blog__single-thumb">
                                <a href="{% url 'web:blog_detail' post.slug %}">
                                    {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                    {% else %}
                                    <img src="{% static 'images/four-7.png' %}" alt="{{ post.title }}">
                                    {% endif %}
                                </a>
                                <div class="tag">
                                    <a href="#"><i class="fa-solid fa-tags"></i> {{ post.category.name|default:"General" }}</a>
                                </div>
                            </div>
                            <div class="blog__single-cta">
                                <a href="{% url 'web:blog_detail' post.slug %}" aria-label="blog details" title="blog details">Read More<i class="fa-solid fa-circle-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12 text-center">
                <p>No blog posts found.</p>
            </div>
            {% endfor %}
        </div>

        <!-- Pagination -->
        {% if is_paginated %}
        <div class="blog-pagination text-center mt-5">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <i class="fa-solid fa-angle-left"></i>
                    </a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <i class="fa-solid fa-angle-right"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/cause-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ program.title }} - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Program Details</span>              
             <h2 class="title-animation">{{ program.title }}</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Program Details Section -->
<section class="program-details section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="program-details__content">
                    <div class="thumb mb-4">
                        {% if program.image %}
                        <img src="{{ program.image.url }}" alt="{{ program.title }}" class="img-fluid rounded">
                        {% else %}
                        <img src="{% static 'images/poster-1.png' %}" alt="{{ program.title }}" class="img-fluid rounded">
                        {% endif %}
                    </div>
                    
                    <div class="meta mb-3">
                        <span class="date"><i class="far fa-calendar-alt"></i> Created on {{ program.created_at|date:"d M Y" }}</span>
                    </div>

                    <h2 class="title mb-4">{{ program.title }}</h2>
                    
                    <div class="description mb-5">
                        {{ program.description|linebreaks }}
                    </div>

                    <div class="summary-box p-4 bg-light rounded mb-5">
                        <h4>Program Summary</h4>
                        <p>{{ program.description|truncatewords:50 }}</p>
                    </div>

                    <div class="row images-grid">
                        <!-- Additional images can be added here if needed -->
                        <div class="col-md-6 mb-4">
                             <img src="{% static 'images/three-10.png' %}" alt="Detail" class="img-fluid rounded">
                        </div>
                        <div class="col-md-6 mb-4">
                             <img src="{% static 'images/two-11.png' %}" alt="Detail" class="img-fluid rounded">
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <aside class="sidebar p-4 bg-white shadow-sm rounded">
                    <div class="donation-stats">
                        <div class="cause__progress progress-bar-single mb-4">
                            <div class="cause-progress__intro">
                                <p><span>Donation Progress</span>
                                    <span class="percent-value">{{ program.get_percentage|floatformat:0 }}%</span>
                                </p>
                            </div>
                            <div class="cause-progress__bar">
                                <div class="progress-bar-wrapper" data-percent="{{ program.get_percentage|floatformat:0 }}%">
                                    <div class="progress-bar">
                                        <div class="progress-bar-percent" style="width:{{ program.get_percentage|floatformat:0 }}%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="cause-progress__goal">
                                <p>Raised: <span class="raised-val">${{ program.raised|default:"0" }}</span></p>
                                <p>Goal: <span class="goal-val">${{ program.goal|default:"0" }}</span></p>
                            </div>
                        </div>
                        <a href="{% url 'web:contact' %}" class="btn--primary w-100 text-center">Donate to this cause <i class="fa-solid fa-arrow-right"></i></a>
                    </div>
                    
                    <div class="recent-posts mt-5">
                        <h5>Latest Blog Posts</h5>
                        <ul class="list-unstyled">
                            {% for post in latest_posts %}
                            <li class="mb-3">
                                <a href="{% url 'web:blog_detail' post.slug %}" class="d-flex align-items-center">
                                    {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="" width="60" class="me-3 rounded">
                                    {% endif %}
                                    <span>{{ post.title }}</span>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/cause.html
{% extends "base.html" %}
{% load static %}

{% block title %}Our Causes - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Help Restore Hope</span>              
             <h2 class="title-animation">Our Causes</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Causes Section -->
<section class="cause section-padding">
    <div class="container">
        <div class="row">
            {% for p in causes %}
            <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                <div class="cause__slider-single">
                    <div class="thumb">
                        <a href="{% url 'web:cause_detail' p.slug %}">
                            {% if p.image %}
                            <img src="{{ p.image.url }}" alt="{{ p.title }}">
                            {% else %}
                            <img src="{% static 'images/1.png' %}" alt="{{ p.title }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="content">
                        <h6><a href="{% url 'web:cause_detail' p.slug %}">{{ p.title }}</a></h6>
                        <p>{{ p.description|truncatewords:15 }}</p>
                    </div>
                    <div class="cause__slider-cta">
                        <div class="cause__progress progress-bar-single">
                            <div class="cause-progress__intro">
                                <p><span>Donation</span>
                                    <span class="percent-value">{{ p.get_percentage|floatformat:0 }}%</span>
                                </p>
                            </div>
                            <div class="cause-progress__bar">
                                <div class="progress-bar-wrapper" data-percent="{{ p.get_percentage|floatformat:0 }}%">
                                    <div class="progress-bar">
                                        <div class="progress-bar-percent" style="width:{{ p.get_percentage|floatformat:0 }}%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="cause-progress__goal">
                                <p>Raised: <span class="raised">${{ p.raised|default:"0" }}</span></p>
                                <p>Goal: <span class="goal">${{ p.goal|default:"0" }}</span></p>
                            </div>
                        </div>
                        <div class="cause__cta">
                            <a href="{% url 'web:cause_detail' p.slug %}" class="btn--secondary">Donate Now</a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12 text-center">
                <p>No causes found.</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/event.html
{% extends "base.html" %}
{% load static %}

{% block title %}Upcoming Events - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Join Our Journey</span>              
             <h2 class="title-animation">Upcoming Events</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Events Section -->
<section class="events-section section-padding">
    <div class="container">
        <div class="row gutter-40">
            {% for event in events %}
            <div class="col-lg-4 col-md-6 mb-5">
                <div class="event-card bg-white shadow-sm rounded overflow-hidden h-100 van-tilt">
                    <div class="event-card__thumb position-relative">
                        {% if event.image %}
                        <img src="{{ event.image.url }}" alt="{{ event.title }}" class="img-fluid w-100">
                        {% else %}
                        <img src="{% static 'images/one-2.png' %}" alt="{{ event.title }}" class="img-fluid w-100">
                        {% endif %}
                        <div class="event-card__date position-absolute top-0 start-0 bg-primary text-white p-2 text-center">
                            <span class="d-block fs-4 fw-bold">{{ event.date|date:"d" }}</span>
                            <span class="d-block text-uppercase">{{ event.date|date:"M" }}</span>
                        </div>
                    </div>
                    <div class="event-card__content p-4">
                        <div class="event-card__meta mb-2 text-muted small">
                            <span class="me-3"><i class="far fa-clock text-primary"></i> {{ event.time|time:"H:i" }}</span>
                            <span><i class="fas fa-map-marker-alt text-primary"></i> {{ event.location }}</span>
                        </div>
                        <h4 class="mb-3"><a href="{% url 'web:event_detail' event.slug %}" class="text-dark">{{ event.title }}</a></h4>
                        <p class="text-muted">{{ event.description|truncatewords:20 }}</p>
                        <a href="{% url 'web:event_detail' event.slug %}" class="btn--link text-primary fw-bold">Read More <i class="fas fa-arrow-right small ms-1"></i></a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12 text-center py-5">
                <div class="empty-state">
                    <i class="far fa-calendar-times fs-1 text-muted mb-3 d-block"></i>
                    <h3>No Upcoming Events</h3>
                    <p class="text-muted">Stay tuned for future updates and community gatherings.</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/program-details.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ program.title }} - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Program Details</span>              
             <h2 class="title-animation">{{ program.title }}</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Program Details Section -->
<section class="program-details section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="program-details__content">
                    <div class="thumb mb-4">
                        {% if program.image %}
                        <img src="{{ program.image.url }}" alt="{{ program.title }}" class="img-fluid rounded">
                        {% else %}
                        <img src="{% static 'images/poster-1.png' %}" alt="{{ program.title }}" class="img-fluid rounded">
                        {% endif %}
                    </div>
                    
                    <div class="meta mb-3">
                        <span class="date"><i class="far fa-calendar-alt"></i> Created on {{ program.created_at|date:"d M Y" }}</span>
                    </div>

                    <h2 class="title mb-4">{{ program.title }}</h2>
                    
                    <div class="description mb-5">
                        {{ program.description|linebreaks }}
                    </div>

                    <div class="row images-grid">
                        <div class="col-md-6 mb-4">
                             <img src="{% static 'images/three-10.png' %}" alt="Detail" class="img-fluid rounded">
                        </div>
                        <div class="col-md-6 mb-4">
                             <img src="{% static 'images/two-11.png' %}" alt="Detail" class="img-fluid rounded">
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4">
                <aside class="sidebar p-4 bg-white shadow-sm rounded">
                    <div class="cta-box text-center">
                        <h5>Want to Support This Program?</h5>
                        <p>Your contribution helps us sustain our ongoing efforts in {{ program.title }}.</p>
                        <a href="{% url 'web:donate' %}" class="btn--primary w-100 text-center">Donate Now <i class="fa-solid fa-arrow-right"></i></a>
                    </div>
                    
                    <div class="recent-posts mt-5">
                        <h5>Latest Blog Posts</h5>
                        <ul class="list-unstyled">
                            {% for post in latest_posts %}
                            <li class="mb-3">
                                <a href="{% url 'web:blog_detail' post.slug %}" class="d-flex align-items-center">
                                    {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="" width="60" class="me-3 rounded">
                                    {% endif %}
                                    <span>{{ post.title }}</span>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/programs.html
{% extends "base.html" %}
{% load static %}

{% block title %}Our Programs - {{ site_settings.site_name }}{% endblock %}

{% block content %}
<!-- Banner section -->
<section class="common-banner">
    <div class="container">
       <div class="row">
          <div class="common-banner__content text-center">
             <span class="sub-title">
             <i class="icon-donation"></i>Empowering Communities</span>              
             <h2 class="title-animation">Our Programs</h2>                  
          </div>
       </div>
    </div>
    <div class="banner-bg">
       <img src="{% static 'images/bc_banner-bg.png' %}" alt="Image">
    </div>
    <div class="shape">
       <img src="{% static 'images/shape.png' %}" alt="Image">
    </div>
    <div class="sprade" data-aos="zoom-in" data-aos-duration="1000">
       <img src="{% static 'images/sprade-base.png' %}" alt="Image" class="base-img">
    </div>
</section>

<!-- Programs Section -->
<section class="cause section-padding">
    <div class="container">
        <div class="row">
            {% for p in programs %}
            <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                <div class="cause__slider-single h-100 d-flex flex-column">
                    <div class="thumb">
                        <a href="{% url 'web:program_detail' p.slug %}">
                            {% if p.image %}
                            <img src="{{ p.image.url }}" alt="{{ p.title }}">
                            {% else %}
                            <img src="{% static 'images/1.png' %}" alt="{{ p.title }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="content flex-grow-1">
                        <h6><a href="{% url 'web:program_detail' p.slug %}">{{ p.title }}</a></h6>
                        <p>{{ p.description|truncatewords:20 }}</p>
                    </div>
                    <div class="cause__cta mt-auto p-3 text-center">
                        <a href="{% url 'web:program_detail' p.slug %}" class="btn--secondary">Explore Program</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12 text-center">
                <p>No programs found.</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}